# Generated by Django 4.2.1 on 2023-05-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_cite', models.CharField(max_length=25)),
                ('adresse', models.CharField(max_length=50)),
            ],
        ),
    ]
