# Generated by Django 4.2.1 on 2023-05-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('cin', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_du_chambre', models.CharField(max_length=30)),
                ('prix_de_location', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('Libre', 'Libre'), ('Occupé', 'Occupé')], max_length=25, null=True)),
                ('addresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.appartement')),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField(null=True)),
                ('fin', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Payé', 'Payé'), ('Non payé', 'Non payé')], max_length=25, null=True)),
                ('dateDePayement', models.DateField(null=True)),
                ('chambre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.chambre')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.client')),
            ],
        ),
    ]
