# Generated by Django 4.2.1 on 2023-05-18 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_client_chambre_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='appartement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.appartement'),
        ),
    ]
