# Generated by Django 4.2.1 on 2023-05-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_abonnement_appartement'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='appart_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/Client/images/'),
        ),
    ]
