# Generated by Django 4.2.1 on 2023-05-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_alter_appartement_appart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='chambre_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
